"""Add sale_price in product

Revision ID: 147a9cbad90c
Revises: 73576be91b35
Create Date: 2026-02-16 18:23:57.989124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147a9cbad90c'
down_revision = '73576be91b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###
