"""Add invoice number in order

Revision ID: 806ae6e0cb89
Revises: 147a9cbad90c
Create Date: 2026-02-24 11:32:50.234827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806ae6e0cb89'
down_revision = '147a9cbad90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
