"""Description of change

Revision ID: cb9bfcc5a4b9
Revises: fda832037b65
Create Date: 2026-02-13 10:00:27.040815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9bfcc5a4b9'
down_revision = 'fda832037b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
