"""Add Bike table and update Product schema for many-to-many relationship

Revision ID: fb0fc1905be7
Revises: cb9bfcc5a4b9
Create Date: 2026-02-16 14:19:40.432988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0fc1905be7'
down_revision = 'cb9bfcc5a4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_bike_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bike_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'bike_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('also_known_as', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('oem_part_no', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('list_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hsn_code', sa.String(), nullable=True))
        batch_op.drop_column('cost_price')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('cost')
        batch_op.drop_column('list_price')
        batch_op.drop_column('oem_part_no')
        batch_op.drop_column('also_known_as')
        batch_op.drop_column('item_name')
        batch_op.drop_column('brand_type')

    op.drop_table('product_bike_association')
    op.drop_table('bikes')
    # ### end Alembic commands ###
