"""Initial commit

Revision ID: fda832037b65
Revises: 
Create Date: 2026-02-13 09:44:01.716323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fda832037b65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('map_location', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('contact_type', sa.String(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('customer_size', sa.String(), nullable=True),
    sa.Column('gst', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.Column('pack_size', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schema_migrations')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('line_total', sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_order_items_order_id'))
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('confirm_price')
        batch_op.drop_column('item_brand')
        batch_op.drop_column('bike_variant')
        batch_op.drop_column('images')
        batch_op.drop_column('bike_year')
        batch_op.drop_column('item_name')
        batch_op.drop_column('bike_brand')
        batch_op.drop_column('mrp')
        batch_op.drop_column('bike_rc_no')
        batch_op.drop_column('bike_cc')
        batch_op.drop_column('procured_from')
        batch_op.drop_column('bike_model')
        batch_op.drop_column('item_colour')
        batch_op.drop_column('item_category')
        batch_op.drop_column('cost')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_charges', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_orders_customer'))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('check_prices')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('check_prices', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_orders_customer'), ['customer_name'], unique=False)
        batch_op.drop_column('status')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('delivery_charges')
        batch_op.drop_column('order_date')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_colour', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bike_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('procured_from', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bike_cc', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bike_rc_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mrp', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bike_brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bike_year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bike_variant', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confirm_price', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_order_items_order_id'), ['order_id'], unique=False)
        batch_op.drop_column('line_total')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('product_id')

    op.create_table('schema_migrations',
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('migration_name', name=op.f('schema_migrations_pkey'))
    )
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
